[package]
name = "rsdu"
version = "0.1.0"
authors = ["mtoohey31 <mtoohey31@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.12"
termion = "1.5"
num_cpus = "1.0"
